openapi: 3.0.0
info:
  title: User management
  version: 1.0.0
paths:
  /users:
    get:
      parameters: 
        - name: page
          in: query
          required: false
          schema:
            type: integer
        - name: size
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: list users found
          content:
            application/json:
              schema:
                type: object
                example: 
                  id: 1
                  name: Alice
                  email: alice@example.com
        '400': 
          description: wrong parameters provided
          content:
            application/json:
              schema:
                type: object
                example:
                  error: "Bad types for provided query parameters"

          

  
